name:        ${project.artifactId}
version:     ${project.version}
description: ${project.description}
authors:     [RoyCurtis]
website:     https://github.com/RoyCurtis/Ankkuri
main:        roycurtis.ankkuri.Ankkuri

commands:
  ankkuri:
    description: Reloads Ankkuri's configuration
    permission: ankkuri.reload
    permission-message: "ยงc*** You don't have permission to reload Ankkuri"
    usage: "ยง7*** ยง3/<command>ยง7 - Reloads Ankkuri (requires permission ankkuri.reload)"

permissions:
  ankkuri.*:
    description: Bypasses all Ankkuri blocks and allows all other Ankkuri permissions
    children:
      ankkuri.bypass.*: true
      ankkuri.reload: true

  ankkuri.reload:
    description: Allows reloading of Ankkuri's config
    default: op

  ankkuri.bypass.*:
    description: Bypasses all Ankkuri blocks
    children:
      ankkuri.bypass.place: true
      ankkuri.bypass.ride: true

  ankkuri.bypass.place:
    description: Allows players to place boats on all non-water surfaces
    default: op
    children:
      ankkuri.bypass.placeonice: true

  ankkuri.bypass.placeonice:
    description: Allows players to place boats on icy surfaces
    default: op

  ankkuri.bypass.ride:
    description: Allows players to ride boats on all non-water surfaces
    default: op
    children:
      ankkuri.bypass.rideonice: true

  ankkuri.bypass.rideonice:
    description: Allows players to ride boats on icy surfaces
    default: op